# Licensed to the Apache Software Foundation (ASF) under one or more contributor license
# agreements. See the NOTICE file distributed with this work for additional information regarding
# copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0.
# You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0
quarkus.grpc.server.port=9000
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DECISION_ENGINE_DATABASE_URL}
quarkus.datasource.username=${DECISION_ENGINE_DATABASE_USERNAME}
quarkus.datasource.password=${DECISION_ENGINE_DATABASE_PASSWORD}
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.mapping.format.global=ignore
quarkus.hibernate-orm.packages=com.forwardmeasure.jpa.identity.entity,com.forwardmeasure.jpa.locking.entity,com.forwardmeasure.jpa.asynctask.entity,com.forwardmeasure.jpa.core.entity,com.forwardmeasure.decisionengine.jpa.entity
decision-engine.valkey.host=${DECISION_ENGINE_VALKEY_HOST}
decision-engine.valkey.port=${DECISION_ENGINE_VALKEY_PORT:6379}
decision-engine.valkey.password=${DECISION_ENGINE_VALKEY_PASSWORD:}
