/*
 * Copyright 2026 Forward Measure
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package golden.customer;

global java.util.Map result;

rule "business-customer"
when
  Map(this["segment"] == "business")
then
  result.put("outcome", "business");
  result.put("dataset", "customer-segmentation");
end

rule "consumer-customer"
when
  Map(this["segment"] == "consumer")
then
  result.put("outcome", "consumer");
  result.put("dataset", "customer-segmentation");
end
